-- plugins/colorschemes.lua
return {
  { "folke/tokyonight.nvim" },
  { "rebelot/kanagawa.nvim" },
  { "EdenEast/nightfox.nvim" },
  { "rose-pine/neovim", name = "rose-pine" },
  { "catppuccin/nvim", name = "catppuccin" },
  { "ellisonleao/gruvbox.nvim" },
  { "Mofiqul/dracula.nvim" },
  { "navarasu/onedark.nvim" },
  { "sainnhe/everforest" },
  { "marko-cerovac/material.nvim" },
  { "shaunsingh/nord.nvim" },
  { "nyoom-engineering/oxocarbon.nvim" },
  {
    "zaldih/themery.nvim",
    config = function()
      require("themery").setup({
        themes = {
          "tokyonight",
          "tokyonight-night",
          "tokyonight-storm",
          "tokyonight-day",
          "kanagawa",
          "kanagawa-wave",
          "kanagawa-dragon",
          "kanagawa-lotus",
          "nightfox",
          "nordfox",
          "dawnfox",
          "duskfox",
          "rose-pine",
          "rose-pine-moon",
          "rose-pine-dawn",
          "catppuccin",
          "catppuccin-mocha",
          "catppuccin-macchiato",
          "catppuccin-frappe",
          "catppuccin-latte",
          "gruvbox",
          "dracula",
          "onedark",
          "onelight",
          "onedark_vivid",
          "everforest",
          "material",
          "material-darker",
          "material-oceanic",
          "nord",
          "oxocarbon",
        },
        livePreview = true,
      })
    end,
  },
}
